config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
                  path("__debug__/", include("debug_toolbar.urls")),
    path('', include('petowner.urls', namespace='petowner')),
    path('', include('pet.urls', namespace='pet')),
    path('', include('core.urls')),
    path('accounts/', include('core.urls')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('accounts/', include('allauth.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pet/urls.py
from django.urls import path

from . import views

app_name = 'pet'

urlpatterns = [
    path('api/pets/<int:pk>/delete', views.PetDeleteAPIView.as_view(), name='api_delete'),
    path('api/pets/temperature', views.PetTemperatureCreateAPIView.as_view(), name='api_temperature'),
    path('api/pets/coordinate', views.PetCoordinateCreateAPIView.as_view(), name='api_coordinate'),
    path('pets/<int:pk>/update', views.PetUpdateView.as_view(), name='update'),
    path('pets/list', views.PetListView.as_view(), name='list'),
]

petowner/urls.py
from django.urls import path

from . import views

app_name = 'petowner'

urlpatterns = [
    path('petowner/<int:pk>/edit/', views.PetOwnerUpdateView.as_view(), name='edit'),
    path('api/petowner/new/', views.PetOwnerCreateAPIView.as_view(), name='new_api'),
    path('api/petowner/<int:pk>/delete', views.PetOwnerDeleteAPIView.as_view(), name='api_delete'),
    path('petowner/<int:pk>/pets', views.PetOwnerPetListView.as_view(), name='pet_list'),
    path('petowner/api/pets/create', views.PetOwnerCreatePetView.as_view(), name='pet_create'),
]

templates/Pages/pet_delete.html
{% extends 'Pages/Shared/_Layout.html' %}
{% block PageContent %}
    {% load static %}
    <div id="page-content">
        <div class="row">
            <!-- BEGIN BREADCRUMB -->
            <div class="col-md-12">
                <div class="breadcrumb-box border shadow">
                    <ul class="breadcrumb">
                        <li><a id="ttlPage" href="#">Delete Pet</a></li>
                    </ul>
                    <div class="breadcrumb-right">

                    <span class="dateToday">
                        Fri, 26 Aug 2022
                    </span>
                        <i class="icon-calendar"></i>
                    </div><!-- /.breadcrumb-right -->
                </div><!-- /.breadcrumb-box -->
            </div><!-- /.col-md-12 -->
            <!-- END BREADCRUMB -->
        </div>

        <div id="gridUser" class="row justify-content-center">
            <div class=" col-lg-10  col-12">
                <div class="portlet box border shadow">
                    <div class="portlet-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col">
                                    <img id="imgProfile1"
                                         src="{% static '' %}{{ object.image }}"
                                         alt="profile image"
                                         class="img-circle img-responsive img_profile_Right VDimgUser">
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col">
                                    Name: {{ object.name }}
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col">
                                    Breed: {{ object.breed }}
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col">
                                    Age: {{ object.age }}
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col">
                                    Birthdate: {{ object.birthdate }}
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col">
                                    ID Number: {{ object.serial_number }}
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col">
                                    <input class="btn btn-danger btn-round" type="submit" value="Delete">
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col">
                                    <a class="btn btn-cyan btn-round" href="{% url 'index' %}">Cancel</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!-- /#page-content -->

        <style>
            .error, .has-error + .help-block, .has-error .checkbox, .has-error .checkbox-inline, .has-error .control-label, .has-error .help-block, .has-error .radio, .has-error .radio-inline, .has-error.checkbox label, .has-error.checkbox-inline label, .has-error.radio label, .has-error.radio-inline label {
                color: #f55145;

            }
        </style>

        <link href="{% static 'assets/plugins/data-table/css/jquery.dataTables.min.css' %}" rel="stylesheet"/>
        <link href="{% static 'assets/plugins/data-table/css/buttons.dataTables.min.css' %}" rel="stylesheet"/>
        <link href="{% static 'assets/plugins/select2/dist/css/select2.min.css' %}" rel="stylesheet">

{% endblock PageContent %}

templates/Pages/pet_list.html
{% extends 'Pages/Shared/_Layout.html' %}
{% block PageContent %}
    {% load static %}
    <div id="page-content">
        <div class="row">
            <!-- BEGIN BREADCRUMB -->
            <div class="col-md-12">
                <div class="breadcrumb-box border shadow">
                    <ul class="breadcrumb">
                        <li><a id="ttlPage" href="#">Pets</a></li>
                    </ul>
                    <div class="breadcrumb-right">

                    <span class="dateToday">
                        Fri, 26 Aug 2022
                    </span>
                        <i class="icon-calendar"></i>
                    </div><!-- /.breadcrumb-right -->
                </div><!-- /.breadcrumb-box -->
            </div><!-- /.col-md-12 -->
            <!-- END BREADCRUMB -->
        </div>

        <div id="gridUser" class="row justify-content-center">


            <div class=" col-lg-10  col-12">
                <div class="portlet box border shadow">

                    <div class="portlet-body">

                        <div i class="table-responsive">
                            <table id="petListTable" class="table table-striped table-bordered dt-responsive nowrap"
                                   width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Type</th>
                                    <th>Breed</th>
                                    <th>Birthdate</th>
                                    <th>Image</th>
                                    <th>ID</th>
                                    <th>Owner</th>
                                    <th>Actions</th>
                                </tr>
                                {% for pet in pets %}
                                    <tr>
                                        <td>{{ pet.name }}</td>
                                        <td>{{ pet.type }}</td>
                                        <td>{{ pet.breed }}</td>
                                        <td>{{ pet.birthdate }}</td>
                                        <td><img src="{{ pet.image.url }}" alt="pet image" width="100px"></td>
                                        <td>{{ pet.serial_number }}</td>
                                        <td>{{ pet.petowner.user.username }}</td>
                                        <td>
                                            <button class="btn btn-sm  DeletT" title="Delete"
                                                    onclick="delete_pet_btn({{ pet.id }}, '{{ pet.name }}')">
                                                <i class="fa fa-remove fa-2x text-danger"></i>
                                            </button>
                                            <a href="{% url 'pet:update' pet.id %}"
                                               class="btn btn-sm  EditT" title="Edit">
                                                <i class="fa fa-edit fa-2x"></i>
                                            </a>
                                            <a href="{% url 'petowner:edit' pet.petowner.user.id %}"
                                               class="btn btn-sm" title="Owner">
                                                <img src="{{ pet.petowner.user.image.url }}" alt="pet owner image"
                                                     class="rounded-circle" width="30" height="30">
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </thead>
                            </table>
                        </div>


                    </div>

                </div>
            </div>


        </div>

    </div><!-- /#page-content -->

    <style>
        .error, .has-error + .help-block, .has-error .checkbox, .has-error .checkbox-inline, .has-error .control-label, .has-error .help-block, .has-error .radio, .has-error .radio-inline, .has-error.checkbox label, .has-error.checkbox-inline label, .has-error.radio label, .has-error.radio-inline label {
            color: #f55145;

        }
    </style>

    <link href="{% static 'assets/plugins/data-table/css/jquery.dataTables.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/plugins/data-table/css/buttons.dataTables.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/plugins/select2/dist/css/select2.min.css' %}" rel="stylesheet">

    <script src="{% static '/js/delete.js' %}"></script>


{% endblock PageContent %}

templates/Pages/pet_temperature_dashboard.html
{% extends 'Pages/Shared/_Layout.html' %}
{% block PageContent %}
    {% load static %}

    <div id="page-content">

        <div class="row">
            <!-- BEGIN BREADCRUMB -->
            <div class="col-md-12">
                <div class="breadcrumb-box border shadow">
                    <ul class="breadcrumb">
                        <li><a id="ttlPage" href="#">Dashboard</a></li>
                    </ul>
                    <div class="breadcrumb-right">

                    <span class="dateToday">
                        Fri, 26 Aug 2022
                    </span>
                        <i class="icon-calendar"></i>
                    </div><!-- /.breadcrumb-right -->
                </div><!-- /.breadcrumb-box -->
            </div><!-- /.col-md-12 -->
            <!-- END BREADCRUMB -->
        </div>


        <div class="row justify-content-center">


            <div class="col-md-3 col-12">

                <div class="form-group">
                    <label for="cmbPetOwnerName">Pet Owner</label>
                    <div class="input-group">

                        <select class="form-control select2 curve" id="cmbPetOwnerName" style="width:100% !important">

                            {% for petowner in petowners %}
                                <option value={{ petowner.user_id }}>{{ petowner.user.get_full_name }}</option>
                            {% endfor %}

                        </select>

                    </div><!-- /.input-group -->
                </div><!-- /.form-group -->
            </div>

            <div class="col-md-3 col-12">

                <div class="form-group">
                    <label for="cmbPetName">Pet</label>
                    <div class="input-group"><select class="form-control select2 curve" id="cmbPetName"
                                                     style="width:100% !important">
                        {#                        {% for pet in pets %}#}
                        {#                            <option value={{ pet.id }} data-owner-id={{ pet.petowner.user_id }}>{{ pet.name }}</option>#}
                        {#                        {% endfor %}#}
                    </select>

                    </div><!-- /.input-group -->
                </div><!-- /.form-group -->
            </div>

            <div class="col-md-4 col-12">
                <button id="btnGo" type="button" class="btn btn-success btn-curve mt-md-4" onclick="petInfoTable()">
                    <i class="icon-check "></i>
                    GO
                </button>
            </div>

        </div><!-- /.modal -->

        <div id="infoRow" class="row ">
            <div class="col">
                <div class="portlet box border shadow">
                    <div class="portlet-body">
                        <div class="table-responsive">
                            <table id="petInfoTable" class="table table-striped" width="100%" height="180"
                                   cellspacing="0" style="height: 40%;">
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
{#            BEGIN THERMOMETER#}
                <div id="thermometer">
                    <div id="temperature"></div>
                </div>
{#            END THERMOMETER#}
            </div>
        </div>
    </div>

    <style>
        .error, .has-error + .help-block, .has-error .checkbox, .has-error .checkbox-inline, .has-error .control-label, .has-error .help-block, .has-error .radio, .has-error .radio-inline, .has-error.checkbox label, .has-error.checkbox-inline label, .has-error.radio label, .has-error.radio-inline label {
            color: #f55145;
        }

        {#BEGIN THERMOMETER STYLE#}
        #thermometer {
            width: 50px;
            height: 200px;
            background: #ccc;
            border-radius: 25px;
            position: relative;
        }

        #temperature {
            position: absolute;
            bottom: 0;
            width: 100%;
            background: linear-gradient(red, yellow, green);
            transition: height 0.5s;
        }
        {#END THERMOMETER STYLE#}

        table {
            width: 100%;
        }

        thead, tbody, tr, td, th {
            display: block;
        }

        tr:after {
            content: ' ';
            display: block;
            visibility: hidden;
            clear: both;
        }

        thead th {
            height: 30px;
            /*text-align: left;*/
        }

        tbody {
            height: 250px;
            overflow-y: auto;
            font-size: 13px;
        }

        thead {
            /* fallback */
        }


        tbody td, thead th {
            width: 33.33%;
            float: left;
            padding-right: 4px !important;
            padding-left: 1px !important;
        }

        thead th {
            margin-bottom: 5px;
            border-style: none
        }

        .preview-textfield {
            position: absolute;
            /*top: 65px;*/
            /*top: 95px;*/
            left: 0;
            right: 0;
            text-align: center;
            font-size: 2em;
            font-weight: bold;
            color: black;
            font-family: 'Amaranth', sans-serif;
        }

        .portlet {
            background: #e9e9e9 !important;
            padding-right: 2px !important;
            padding-left: 2px !important;
        }
    </style>


    <link href="{% static 'assets/plugins/data-table/css/jquery.dataTables.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/plugins/data-table/css/buttons.dataTables.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/plugins/select2/dist/css/select2.min.css' %}" rel="stylesheet">

    <script src="{% static 'assets/plugins/select2/dist/js/select2.full.min.js' %}"></script>
    <script src="{% static 'assets/plugins/select2/dist/js/i18n/fa.js' %}"></script>
    <script src="{% static 'assets/js/pages/select2.js' %}"></script>
    <script src="{% static 'assets/plugins/data-table/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'assets/plugins/data-table/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'assets/plugins/jquery-validation/dist/jquery.validate.min.js' %}"></script>
    <script src="{% static 'assets/js/pages/validation.js' %}"></script>
    <script src="{% static 'assets/js/Chart.min.js' %}"></script>
    {#    <script src="https://bernii.github.io/gauge.js/dist/gauge.js"></script>#}
    {#    <script src="{% static 'assets/js/gauge.js' %}"></script>#}
    <script src="{% static 'assets/js/myDashboard.js' %}"></script>

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
          integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
          crossorigin=""/>

    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
            integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
            crossorigin=""></script>
    <script src="{% static 'assets/plugins/jquery/dist/jquery-3.1.0.js' %}"></script>


    <script>
        function getTopTemperature() {
            var table = document.getElementById('petInfoTable');
            if (table.rows.length > 0) {
                var firstRow = table.rows[1];
                var temperatureCell = firstRow.cells[0];
                var topTemperature = temperatureCell.textContent || temperatureCell.innerText;
                return topTemperature;
            } else {
                return null;
            }
        }

        function setTemperature() {
            var temp = getTopTemperature();
            console.log(temp);
            var thermometer = document.getElementById('temperature');
            var newHeight = temp + "px";
            thermometer.style.height = newHeight;
        }

        function petInfoTable() {
            var petId = $("#cmbPetName").val();
            $.ajax({
                url: '/dashboard/info/',
                data: {
                    'pet_id': petId
                },
                dataType: 'json',
                success: function (data) {
                    if (data.success) {
                        // hide table if data is empty
                        if (data.pet_info.length == 0) {
                            $("#infoRow").hide();
                        }
                        else {
                            $("#infoRow").show();
                        }
                        var table = $("#petInfoTable");
                        table.empty();  // Clear the table
                        var headers = $("<thead></thead>");
                        headers.append("<tr><th>Temperature</th><th>Date</th></tr>")
                        table.append(headers);
                        var body = $("<tbody></tbody>");
                        table.append(body);

                        $.each(data.pet_info, function (index, element) {
                            var row = $("<tr></tr>");
                            row.append($("<td></td>").text(element.temperature));
                            row.append($("<td></td>").text(element.date));
                            table.append(row);
                        });
                    } else {
                        alert("Error retrieving pet information.");
                    }
                }
            });
            setTemperature();
        }

        function getPets() {
            console.log('get pets');
            let petowner_id = document.getElementById("cmbPetOwnerName").value;
            $.ajax({
                url: '{% url 'dashboard_pets' %}',
                data: {
                    'petowner_id': petowner_id
                },
                dataType: 'json',
                success: function (data) {
                    console.log(data.pets);
                    let petList = document.getElementById("cmbPetName");
                    petList.innerHTML = "";
                    $.each(data.pets, function (index, element) {
                        let option = document.createElement("option");
                        option.value = element.id;
                        option.text = element.name;
                        petList.appendChild(option);
                    });
                }
            });
        }

        document.getElementById("cmbPetOwnerName").addEventListener("change", function () {
            getPets();
            petInfoTable();
        });

        $(document).ready(function () {
            getPets();
            petInfoTable();
            myVar = setInterval("petInfoTable()", 1000);
        });

    </script>

{% endblock PageContent %}

templates/Pages/petowner_delete.html
{% extends 'Pages/Shared/_Layout.html' %}
{% block PageContent %}
    {% load static %}
    <div id="page-content">
        <div class="row">
            <!-- BEGIN BREADCRUMB -->
            <div class="col-md-12">
                <div class="breadcrumb-box border shadow">
                    <ul class="breadcrumb">
                        <li><a id="ttlPage" href="#">Delete Pet owner</a></li>
                    </ul>
                    <div class="breadcrumb-right">

                    <span class="dateToday">
                        Fri, 26 Aug 2022
                    </span>
                        <i class="icon-calendar"></i>
                    </div><!-- /.breadcrumb-right -->
                </div><!-- /.breadcrumb-box -->
            </div><!-- /.col-md-12 -->
            <!-- END BREADCRUMB -->
        </div>

        <div id="gridUser" class="row justify-content-center">
            <div class=" col-lg-10  col-12">
                <div class="portlet box border shadow">
                    <div class="portlet-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col">
                                    <img id="imgProfile1"
                                         src="{% static '' %}{{ object.image }}"
                                         alt="profile image"
                                         class="img-circle img-responsive img_profile_Right VDimgUser">
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col">
                                    Full name: {{ object.first_name }} {{ object.last_name }}
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col">
                                    <input class="btn btn-danger btn-round" type="submit" value="Delete">
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col">
                                    <a class="btn btn-cyan btn-round" href="{% url 'index' %}">Cancel</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!-- /#page-content -->

        <style>
            .error, .has-error + .help-block, .has-error .checkbox, .has-error .checkbox-inline, .has-error .control-label, .has-error .help-block, .has-error .radio, .has-error .radio-inline, .has-error.checkbox label, .has-error.checkbox-inline label, .has-error.radio label, .has-error.radio-inline label {
                color: #f55145;

            }
        </style>

        <link href="{% static 'assets/plugins/data-table/css/jquery.dataTables.min.css' %}" rel="stylesheet"/>
        <link href="{% static 'assets/plugins/data-table/css/buttons.dataTables.min.css' %}" rel="stylesheet"/>
        <link href="{% static 'assets/plugins/select2/dist/css/select2.min.css' %}" rel="stylesheet">

{% endblock PageContent %}